### ISSUE TITLE
Link validator fails on datastax pages

### ISSUE THREAD

**Issue by raboof** [apache/pekko-projection#178]
Like a 404 for https://docs.datastax.com/en/cql-oss/3.x/cql/cql_reference/counter_type.html on https://pekko.apache.org/docs/pekko-projection/current/getting-started/projection-handler.html - but that page seems fine to me? do we understand what's going on there?

**Comment by pjfanning** [comment]
#183 merged

Feel free to reopen if you feel we need to do a deep dive into why link validator reports issues even though the links in the web pages work.
