### ISSUE TITLE
Is a next release planned?

### ISSUE THREAD

**Issue by tiagomota** [apache/pekko-projection#198]
Hey 👋 

First of all, thanks for your hard work maintaining this project! It is highly appreciated 🙏 

I've noticed that the support for Scala 3 has been merged in #167, however no release has been made with these updates.
Is there a reason for it that I missed? If not, are you planning on releasing in the near future?

Thanks in advance 🙏

**Comment by pjfanning** [comment]
The only pekko-projection module that isn't released for Scala 3 is pekko-projection-slick.
pekko-projection-slick is deprecated. Please see https://pekko.apache.org/docs/pekko-projection/current/slick.html
We will still do new releases for pekko-projection-slick but they are not as high priority as other more commonly used libs.

I am hoping to start doing v1.1.0 releases for Pekko modules soon but it could take a while to get to pekko-projection. It requires that we release most of our other modules first. We have v1.1.0-M1 releases for most modules but not for pekko-projection and at this stage, I think the community benefits more from us starting v1.1.0 releases. Releases are non trivial events requiring release management, reviews and votes.

So - would you consider switching to pekko-projection-jdbc? If you are stuck with pekko-projection-slick, could you consider building the classes for yourself? On a quick check, I only found 4 source files in src/main plus the reference.conf.

**Comment by tiagomota** [comment]
I see. Thanks for the explanation 🙏 

On our side, the goal is to enable team to start to upgrade our projects/services to Scala 3.
 
Since we use other projects that rely on slick, when upgrading those we get a conflict with `pekko-projection-slick` as it is bringing an older version of slick (`3.4.1`) which does not support Scala 3. Having a release of `pekko-projection-slick` with slick `3.5.x` would then be super helpful to us.

However, thanks for the suggestion! We will further explore our options.

**Comment by pjfanning** [comment]
I've created an RC and started a vote. There are no guarantees that people will be available to review this RC.

https://lists.apache.org/thread/0cwds71rtpzokcpy1v4npkjbkdhtkqow

**Comment by tiagomota** [comment]
It is highly appreciated @pjfanning! Thanks 🙏

**Comment by mdedetrich** [comment]
> The only pekko-projection module that isn't released for Scala 3 is pekko-projection-slick.
> pekko-projection-slick is deprecated. Please see https://pekko.apache.org/docs/pekko-projection/current/slick.html
> We will still do new releases for pekko-projection-slick but they are not as high priority as other more commonly used libs.

Did we deprecate this ourselves or was pekko-projection-slick always deprecated?

**Comment by pjfanning** [comment]
Deprecated before we forked.

**Comment by mdedetrich** [comment]
> Deprecated before we forked.

Okay, would be good to look into the reasons why (my immediate suspicion is due to Slick becoming a community project).

**Comment by raboof** [comment]
I don't know/remember - did we think pekko-projection-jdbc would be sufficient / more suitable for projections?

**Comment by pjfanning** [comment]
1.1.0-M1 is released. It will take a few months to get to a 1.1.0 release because we have to release all the core modules first.

**Comment by tiagomota** [comment]
This is highly appreciated! Thanks a lot to everyone involved 🙏
